# Change these first
owner: HealingMercury # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://zgriffin.com
  - name: Toolbox
    url: https://toolbox.zgriffin.com

status-website:
  cname: status.zgriffin.com
  logoUrl: https://cdn.zgriffin.com/images/logo.png
  name: Status
  introTitle: "ZG Status"
  introMessage: "Status page for applications under the within the zgriffin ecosystem"
  navbar:
    - title: Status
      href: /
  i18n:
    footer: "ZACH GRIFFIN STATUS"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
