# Change these first
owner: HealingMercury # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://zgriffin.com
  - name: Toolbox
    url: https://toolbox.zgriffin.com

status-website:
  cname: status.zgriffin.com
  logoUrl: https://cdn.zgriffin.com/images/logo.png
  name: Status
  theme: light
  introTitle: "ZG Status"
  introMessage: "Status page for applications under the within the zgriffin ecosystem"
  navbar:
    - title: Status
      href: /
  i18n:
    footer: "ZACH GRIFFIN STATUS"
  runner: "[self-hosted, linux, ARM64]"
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 * * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
